from .version import __VERSION__, __NAME__, __DESCRIPTION__
from .globals import (
    RABBIT_MODE,
    FTG_PLUGIN_ROOT_PATH,
    FTG_HUD_DESC,
    FTG_HUD,
    FTG_CANCEL_COMMAND,
    FTG_CANCEL_COMMAND_DESC,
    FTG_OK_COMMAND,
    FTG_CLEARANCE_COMMAND,
    FTG_CLEARANCE_COMMAND_DESC,
    FTG_IS_RUNNING,
    FTG_OK_COMMAND_DESC,
    FTG_SPEED_COMMAND,
    FTG_SPEED_COMMAND_DESC,
    FTG_COMMAND,
    FTG_COMMAND_DESC,
    FTG_BOOKMARK_COMMAND,
    FTG_BOOKMARK_COMMAND_DESC,
    FTG_NEWGREENS_COMMAND,
    FTG_NEWGREENS_COMMAND_DESC,
    FTG_MENU,
    STW_COMMAND,
    STW_COMMAND_DESC,
    STW_MENU,
)
from .followthegreens import FollowTheGreens
from .showtaxiways import ShowTaxiways
